// <auto-generated />
using CrowdLens.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Crowdlens_backend.Migrations
{
    [DbContext(typeof(CrowdLensDbContext))]
    [Migration("20260424000001_AddFavoritesTable")]
    partial class AddFavoritesTable
    {
    }
}
